HiddifyPanel/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.generic.base import RedirectView
from bot_connection.webhook import webhook
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('webhook/', webhook, name='webhook'),
    path("", RedirectView.as_view(url="accounts/home/bot/", permanent=False)),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
    path("bot_finance/", include("bot_finance.urls", namespace="bot_finance")),
    path("bot_customers/", include("bot_customers.urls", namespace="bot_customers")),
    path("servers/", include("servers.urls", namespace="servers")),
    path("bot_config/", include("bot_config.urls", namespace="bot_configs")),
    path("sellers_config/", include("sellers_config.urls", namespace="sellers_configs")),
    path("sellers_finance/", include("sellers_finance.urls"), name="sellers_finance"),
    path("sellers_connection/", include("sellers_connection.urls", namespace="sellers_connection")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot_customers/urls.py
from django.urls import path
from . import views

app_name = "bot_customers"

urlpatterns = [
   path("custumers_list/", views.CustomerList.as_view(), name="custumers_list"),
   path("custumer_detail/<int:customer_id>/", views.CustomerDetail.as_view(), name="custumer_detail"),
   path("send_msg_to_all/", views.SendMsgToAll.as_view(), name="send_msg_to_all"),
   path("send_msg_to_Custumer/<int:userid>/", views.SendMsgToUser.as_view(), name="send_msg_to_user"),
   path("change_wallet/<int:userid>/", views.ChangeWalletAmount.as_view(), name="change_wallet"),
   path("update_customer/<int:userid>/", views.UpdateCustumer.as_view(), name="update_customer"),
   path("register_conf_for_customer/<str:conf_uuid>/", views.RegisterConfigToCustumer.as_view(), name="register_conf_for_customer"),
   path("ban_user/<int:userid>/", views.BanUser.as_view(), name="ban_user"),
]

bot_finance/urls.py
from django.urls import path
from . import views

app_name = "bot_finance"

urlpatterns = [
    path('confirm_payment/<int:show_box>/', views.ConfirmPaymentPage.as_view(), name='confirm_payments'),
    path('first_confirm_payment/<int:obj_id>/', views.FirstConfirmPayment.as_view(), name='first_confirm'),
    path('secoend_confirm_payment/<int:obj_id>/', views.SecondConfirmPayment.as_view(), name='second_confirm'),
    path('first_tamdid_confirm_payment/<int:obj_id>/', views.FirstTamdidConfirmPayment.as_view(), name='first_tamdid_confirm'),
    path('secoend_tamdid_confirm_payment/<int:obj_id>/', views.SecondTamdidConfirmPayment.as_view(), name='second_tamdid_confirm'),

    path('deny_tamdid_payment_after_first_confirm/<int:obj_id>/', views.DenyTamdidPaymentAfterFirsConfirmPage.as_view(),
         name='deny_tamdid_payments_after_first_confirm'),
    path('deny_payment_after_first_confirm/<int:obj_id>/', views.DenyPaymentAfterFirsConfirmPage.as_view(), name='deny_payments_after_first_confirm'),
    path('deny_payment/<int:obj_id>/<str:typ>/', views.DenyPaymentPage.as_view(), name='deny_payments'),
    path('edit_price_payment/<int:obj_id>/<str:typ>/', views.EditPricePayment.as_view(), name='edit_price'),
    path("paid_after_create/<int:obj_id>/", views.PayedAfterCreate.as_view(), name="paid_after_create"),

    path('show_prices/', views.ShowPrices.as_view(), name='show_prices'),
    path('delete_or_edit_price/<int:obj_id>/<str:action>/', views.DeleteOrEditPrice.as_view(), name='delete_or_edit_price'),
    path('add_price/', views.AddPrice.as_view(), name='add_price'),

    path("show_off_codes/", views.ShowOffCodes.as_view(), name='show_off_codes'),
    path("add_off_codes/", views.AddOffCode.as_view(), name='add_off_codes'),
    path("delete_off_code/<str:uuid>/", views.DeleteOffCode.as_view(), name='delete_off_code'),

]

servers/urls.py
from django.urls import path
from . import views

app_name = 'servers'

urlpatterns = [
    path('show_servers/', views.ShowServers.as_view(), name="show_servers"),
    path("add_server/", views.AddServer.as_view(), name="add_server"),
    path("edit_server/<int:server_id>/", views.EditServer.as_view(), name="edit_server"),
]

bot_finance/models.py
from django.db import models

# Create your models here.
import uuid

from django.db import models
from bot_customers.models import Customer
from bot_config.models import BotConfigInfo


class ConfirmPaymentQueue(models.Model):
    custumer = models.ForeignKey(Customer, on_delete=models.DO_NOTHING)
    pay_price = models.PositiveIntegerField()
    config_price = models.PositiveIntegerField(default=0, null=True, blank=True)
    pay_date = models.DateField(null=True, blank=True)
    status = models.PositiveIntegerField(default=0,
                                         choices=[(0, "waiting for upload picture"), (1, "waiting for confirmation"),
                                                  (2, "first confirme"), (3, "second confirm"), (10, "denied")])
    config_in_queue = models.BooleanField(default=False)
    image = models.ImageField(upload_to='payment_images/', blank=True, null=True)
    deny_reseon = models.CharField(max_length=100, blank=True, null=True)
    config_uuid = models.UUIDField(unique=True, blank=True, null=True)
    timestamp = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return str(self.custumer.chat_id)


class ConfirmTamdidPaymentQueue(models.Model):
    config = models.ForeignKey(BotConfigInfo, on_delete=models.CASCADE)
    pay_price = models.PositiveIntegerField()
    config_price = models.PositiveIntegerField(default=0, null=True, blank=True)
    pay_date = models.DateField(null=True, blank=True)
    status = models.PositiveIntegerField(default=0,
                                         choices=[(0, "waiting for upload picture"), (1, "waiting for confirmation"),
                                                  (2, "first confirme"), (3, "second confirm"), (10, "denied")])
    image = models.ImageField(upload_to='payment_images/', blank=True, null=True)
    deny_reseon = models.CharField(max_length=100, blank=True, null=True)
    timestamp = models.PositiveBigIntegerField(default=0)

    def __str__(self):
        return str(self.config.name)


class Prices(models.Model):
    usage_limit = models.PositiveIntegerField()
    expire_limit = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    user_limit = models.PositiveIntegerField(default=0)


class OffCodes(models.Model):
    uid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    type_off = models.IntegerField(choices=[(0, "amount"), (1, "percent")])
    amount = models.PositiveIntegerField()
    customer_count = models.PositiveIntegerField()
    use_count = models.PositiveIntegerField()
    create_timestamp = models.PositiveBigIntegerField()
    end_timestamp = models.PositiveBigIntegerField()
    for_infinit_usages = models.BooleanField()
    for_infinit_times = models.BooleanField()
    for_not_infinity = models.BooleanField()


class UserActiveOffCodes(models.Model):
    off_code = models.ForeignKey(OffCodes, on_delete=models.CASCADE)
    custumer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    used = models.BooleanField(default=False)


class CreateConfigQueue(models.Model):
    custumer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    config_uuid = models.UUIDField(unique=True)
    config_name = models.CharField(max_length=50, unique=True)
    usage_limit = models.IntegerField()
    expire_time = models.IntegerField()
    user_limit = models.IntegerField()
    price = models.IntegerField()
    sent_to_user = models.IntegerField(default=0, choices=[(0, "Created"), (1, "pending"), (2, "sent"), (5, "Faild")])
    pay_status = models.PositiveSmallIntegerField(default=0, choices=[
        (0, "waiting for pay img"), (1, "waiting for confirm"), (2, "first confirmed"), (3, "secoend confirm"),
        (10, "denied")
    ])

    def __str__(self):
        return self.config_name


class TamdidConfigQueue(models.Model):
    config = models.ForeignKey(BotConfigInfo, on_delete=models.CASCADE)
    usage_limit = models.IntegerField()
    expire_time = models.IntegerField()
    user_limit = models.IntegerField()
    price = models.IntegerField()
    sent_to_user = models.IntegerField(default=0, choices=[(0, "Created"), (1, "pending"), (2, "sent"), (5, "Faild")])
    pay_status = models.PositiveSmallIntegerField(default=0, choices=[
        (0, "waiting for pay img"), (1, "waiting for confirm"), (2, "first confirmed"), (3, "secoend confirm"),
        (10, "denied")
    ])

    def __str__(self):
        return self.config.name

bot_finance/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Prices


class DenyForm(forms.Form):
    reason = forms.CharField(widget=forms.Textarea, max_length=100)
    delete_all_configs = forms.BooleanField(required=False)
    disable_all_configs = forms.BooleanField(required=False)
    ban_user = forms.BooleanField(required=False)




class AddPriceForm(forms.Form):
    type_conf = forms.ChoiceField(choices=[("limited", "حجمی"), ("inf_usage", "حجم نامحدود"), ("inf_time", "زمان نامحدود")])
    usage = forms.IntegerField(initial=0)
    month = forms.ChoiceField(choices=[(1,"1 ماه"),(2,"2 ماه"),(3,"3 ماه"),(6,"6 ماه")])
    ip_limit = forms.ChoiceField(choices=[(1,"1 کاربره"),(2,"2 کاربره")])
    price = forms.IntegerField(required=True)

    def clean(self):
        price = self.cleaned_data.get('price')
        usage = self.cleaned_data.get('usage')
        type_conf = self.cleaned_data.get('type_conf')
        ip_limit = self.cleaned_data.get('ip_limit')
        month = self.cleaned_data.get('month')
        if price:
            if not 10 < price < 999 :
                raise ValidationError('قیمت باید بین 10 تا 999 هزار تومان باشد.')
        else:
            raise ValidationError("قیمت را وارد کنید.")
        if type_conf == "limited" or type_conf == 'inf_time':
            if not 2 < usage < 900:
                raise ValidationError("حجم کانفیگ باید بین 2 تا 900 گیگ باشد.")

        if type_conf == "limited":
            ip_limit = 0
        elif type_conf == "inf_usage":
            usage = 0
        elif type_conf == "inf_time":
            month = 0
        if Prices.objects.filter(
                user_limit=int(ip_limit),
                usage_limit=int(usage),
                expire_limit=int(month)).exists():
            raise ValidationError("این تعرفه قبلا ثبت شده است.")

class EditPriceForm(forms.Form):
    price = forms.IntegerField(required=True,widget=forms.TextInput(attrs={'placeholder': 'قیمت جدید / هزارتومان'}))
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price:
            if not 5 < price < 999:
                raise ValidationError('قیمت باید بین 5 تا 999 هزار تومان باشد.')
        else:
            raise ValidationError("قیمت را وارد کنید.")
        return price * 1000


class AddOffForm(forms.Form):
    type_off = forms.ChoiceField(choices=[(1, "درصدی (%)"), (0, "مقداری (تومان)")], required=False)
    amount = forms.IntegerField(min_value=1, max_value=50, required=False)
    curumer_count = forms.IntegerField(initial=0, min_value=0 , max_value=500, required=False)
    use_count = forms.ChoiceField(choices=[(1, "1 بار"),(0,"چندین بار")])
    end_time = forms.ChoiceField(choices=[(1,"1 روز"), (2,"2 روز"), (3,"3 روز"), (5,"5 روز"), (7,"7 روز"), (10,"10 روز"), (20,"20 روز"), (30,"30 روز"), (60,"60 روز")], required=False)
    for_infinit_usages = forms.BooleanField(initial=True, required=False)
    for_infinit_times = forms.BooleanField(initial=True, required=False)
    for_not_infinity = forms.BooleanField(initial=True, required=False)

    def clean(self):
        amount = self.cleaned_data.get('amount')
        print(amount)
        if not amount:
            raise ValidationError("مقداد تخفیف را وارد کنید.")

bot_finance/templates/add_off_code.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bot_finance/add_price.css' %}">
</head>
<body>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let type = document.querySelector('#id_type_off');
        let usage = document.querySelector('#typ1');
        let ip_limit = document.querySelector('#typ0');

        function toggleexpireField() {
            if (type.value === '0') {
                usage.style.display = "block"
                ip_limit.style.display = "none"
            }
            else if (type.value === '1'){
                usage.style.display = "none"
                ip_limit.style.display = "block"
            }

        }

        type.addEventListener('change', toggleexpireField);
        toggleexpireField();
    });
</script>
    {% include "navbar_bot.html" %}
    <div id="main">
        <form novalidate action="" method="post" dir="rtl">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
            <h3 id="title">کد تخفیف جدید</h3>
            {% csrf_token %}
            <div class="textinput item"><h3 class="item_text">نوع تخفیف : </h3>{{ form.type_off }}</div>
            <div class="textinput item"><h3 class="item_text">مقدار : </h3>{{ form.amount }} <span id="typ0">درصد</span><span id="typ1">هزار تومان</span></div>
            <div class="textinput item"><h3 class="item_text"> تعداد یوزر هایی که میتوانند استفاده کنند : </h3>{{ form.curumer_count }} <span style="display: block"> 0 = تعداد نامحدود </span></div>
            <div class="textinput item"><h3 class="item_text"> تعداد دفعاتی که هر یوزر میتواند استفاده کند : </h3>{{ form.use_count }}</div>
            <div class="textinput item"><h3 class="item_text">مدت زمان اجازه ثبت : </h3>{{ form.end_time }}</div>
            <div class="textinput item"><h3 class="item_text">کانفیک های حجمی : </h3>{{ form.for_not_infinity }}</div>
            <div class="textinput item"><h3 class="item_text">کانفیک های حجم نامحدود : </h3>{{ form.for_infinit_usages }}</div>
            <div class="textinput item"><h3 class="item_text">کانفیک های زمان نامحدود : </h3>{{ form.for_infinit_times }}</div>

            <input id="create" type="submit" value="Create" class="submit_btn">
        </form>
    </div>
{% include "loading.html" %}
    <style>
        #id_amount,#id_type_off, #id_curumer_count, #id_use_count, #id_end_time {
            width: 50%;
            text-align: center;
        }
        #id_for_not_infinity, #id_for_infinit_usages, #id_for_infinit_times {
            width: 1rem;
            height: 2rem;
            margin-top: 0;
        }
    </style>

</body>
</html>

bot_finance/templates/confirm_payment.html
{% load compress %}
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bot_finance/confirm_payment.css' %}">
    <script>
        $(document).ready(function() {
            $("#loading").hide()
            $(".item").click(function () {
                $("#main").hide();
                $("#loading").show();
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            {% if show_box == 1 %}
                $("#box1").show();
                $("#box2").hide();
                $("#box3").hide();
                $("#btn1").css({"background-color": "#000d3f", "color":"white"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            {% elif show_box == 2 %}
                $("#box1").hide();
                $("#box2").show();
                $("#box3").hide();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "#000d3f", "color":"white"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            {% elif show_box == 3 %}
                $("#box1").hide();
                $("#box2").hide();
                $("#box3").show();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "#000d3f", "color":"white"})
            {% endif %}


            $("#btn1").click(function () {
                $("#box1").show();
                $("#box2").hide();
                $("#box3").hide();
                $("#btn1").css({"background-color": "#000d3f", "color":"white"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            });
            $("#btn2").click(function () {
                $("#box1").hide();
                $("#box2").show();
                $("#box3").hide();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "#000d3f", "color":"white"})
                $("#btn3").css({"background-color": "white", "color":"#000d3f"})
            });
            $("#btn3").click(function () {
                $("#box1").hide();
                $("#box2").hide();
                $("#box3").show();
                $("#btn1").css({"background-color": "white", "color":"#000d3f"})
                $("#btn2").css({"background-color": "white", "color":"#000d3f"})
                $("#btn3").css({"background-color": "#000d3f", "color":"white"})
            });
        });
    </script>
</head>
<body>
    {% include "navbar_bot.html" %}
    {% include 'messages.html' %}
    <div id="main">
        <div id="changebox" dir="rtl">
            <button class="changebtns" id="btn1"> تایید پرداخت<span class="number_not">{{ confirm_count }}</span></button>
            <button class="changebtns" id="btn2"> تایید نهایی <span class="number_not">{{ second_confirm_count }}</span></button>
            <button class="changebtns" id="btn3"> پرداخت بدهی<span class="number_not">{{ not_paid_count }}</span></button>
        </div>
        <div id="box1">
            {% for i in confirm %}
                <div class="paybox" >
                    <div class="pay_info">
                        <div class="infobox">
                            {% if i.config_in_queue %}
                                <h4 class="info">Buy Service</h4>
                            {% else %}
                                <h4 class="info">Add To Wallet</h4>
                            {% endif %}
                            <h3 class="info">userid: <a href="{% url "bot_customers:custumer_detail" i.custumer.chat_id %}" style="color: #98e2ff">{{ i.custumer.chat_id }}</a></h3>
                            <h3 class="info">price : <span class="nspan">{{ i.pay_price|price }} T</span></h3>

                        </div>
                        <div class="conf_btns">

                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:first_confirm' i.id %}" class="confirm c_btnd">تایید اولیه</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:second_confirm' i.id %}" class="sec_confirm c_btnd">تایید نهایی</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:edit_price' i.id "buy" %}" class="edit_price c_btnd">تغییر قیمت</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:deny_payments' i.id "buy" %}" class="deny c_btnd">عدم تایید</a>
                            </div>
                        </div>
                    </div>
                    <img class="pay_img" src="{{ i.image.url }}" alt="pay_img">
                </div>
            {% endfor %}
            {% for i in confirm_tamdid_pay %}
                <div class="paybox" >
                    <div class="pay_info">
                        <div class="infobox">
                            <h4 class="info">Renew: <a style="color: #98e2ff" href="{% url "servers:conf_page" i.config.server.server_id i.config.config_uuid i.config.config_name %}">{{ i.config.config_name }}</a></h4>
                            <h3 class="info">userid: <a href="{% url "bot_customers:custumer_detail" i.config.customer.chat_id %}" style="color: #98e2ff">{{ i.config.customer.chat_id }}</a></h3>
                            <h3 class="info">price : <span class="nspan">{{ i.pay_price|price }} T</span></h3>

                        </div>
                        <div class="conf_btns">

                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:first_tamdid_confirm' i.id %}" class="confirm c_btnd">تایید اولیه</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:second_tamdid_confirm' i.id %}" class="sec_confirm c_btnd">تایید نهایی</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:edit_price' i.id "tamdid" %}" class="edit_price c_btnd">تغییر قیمت</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:deny_payments' i.id "tamdid" %}" class="deny c_btnd">عدم تایید</a>
                            </div>
                        </div>
                    </div>
                    <img class="pay_img" src="{{ i.image.url }}" alt="pay_img">
                </div>
            {% endfor %}
        </div>
        <div id="box2">
            {% for i in second_confirm %}
                <div class="paybox" >
                    <div class="pay_info">
                        <div class="infobox">
                            <h3 class="info">userid:<a style="color: #98e2ff" href="{% url "bot_customers:custumer_detail" i.custumer.chat_id %}"> {{ i.custumer.chat_id }}</a></h3>
                            <h3 class="info">price : <span class="nspan">{{ i.pay_price|price }} T</span></h3>

                        </div>
                        <div class="conf_btns">
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:second_confirm' i.id %}" class="sec_confirm c_btnd">تایید نهایی</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:deny_payments_after_first_confirm' i.id %}" class="deny c_btnd">عدم تایید</a>
                            </div>
                        </div>
                    </div>
                    <img class="pay_img" src="{{ i.image.url }}" alt="pay_img">
                </div>
            {% endfor %}
            {% for i in second_tamdid_pay %}
                <div class="paybox" >
                    <div class="pay_info">
                        <div class="infobox">
                            <h3 class="info">userid:<a style="color: #98e2ff" href="{% url "bot_customers:custumer_detail" i.config.customer.chat_id %}"> {{ i.config.customer.chat_id }}</a></h3>
                            <h3 class="info">price : <span class="nspan">{{ i.pay_price|price }} T</span></h3>

                        </div>
                        <div class="conf_btns">
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:second_tamdid_confirm' i.id %}" class="sec_confirm c_btnd">تایید نهایی</a>
                            </div>
                            <div class="confirmbtn">
                                <a href="{% url 'bot_finance:deny_tamdid_payments_after_first_confirm' i.id %}" class="deny c_btnd">عدم تایید</a>
                            </div>
                        </div>
                    </div>
                    <img class="pay_img" src="{{ i.image.url }}" alt="pay_img">
                </div>
            {% endfor %}
        </div>

        <div id="box3">
            {% for i in not_paid %}
                <div class="xy">
                    <div class="fbox">
                    {% if i.renew_count == 0 %}
                        <h3 class="ttt">Buy Service</h3>
                    {% else %}
                        <h3 class="ttt">Renew Service</h3>
                    {% endif %}
                        <a href="{% url "servers:conf_page" i.server.server_id i.config_uuid i.config_name %}" class="notpaid_text">Service: <span class="nspan" style="color: #98E2FFFF">{{ i.config_name }}</span> </a>
                        <h3 class="notpaid_text">price:  <span class="nspan">{{ i.price|price }} T</span></h3>
                        {% if i.chat_id == none %}
                            <h3 class="notpaid_text">user:  <span class="nspan">----</span></h3>
                        {% else %}
                            <a href="{% url "bot_customers:custumer_detail" i.customer.chat_id %}" class="notpaid_text">user:  <span style="color: #98E2FFFF" class="nspan">{{ i.customer.chat_id }}</span></a>
                        {% endif %}
                    </div>
                    <div class="pbox">
                        <a href="{% url "bot_finance:paid_after_create" i.id %}" class="confirm x_btnd">پرداخت شده</a>
                        <a href="" class="disable x_btnd">غیرفعال کانفیگ</a>
                        <a href="" class="deny x_btnd">حذف کانفیگ</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% include "loading.html" %}

</body>
</html>

bot_finance/templates/show_off_codes.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="fa" class="no-js">
	<head>
		<title>List Configs</title>
        {% include "base_head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'component.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'bot_finance/surathesab_page.css' %}"/>
    </head>
	<body dir="ltr">
        {% include "navbar_bot.html" %}
        {% include 'messages.html' %}
        <div id="main">
            <div class="addbox">
                <a href="{% url 'bot_finance:add_off_codes' %}" class="addprice">➕ جدید</a>
            </div>
            <h3 id="counter">لیست کدهای تخفیف</h3>
		    <div class="xcontainer">
		    		<table class="overflow-y">
		    			<thead>
		    				<tr>
                                <th>UUID</th>
                                <th>مقدار</th>
                                <th>تعداد کابر</th>
                                <th>استفاده هرکابر</th>
                                <th>تاریخ ساخت</th>
                                <th>تاریخ اتمام</th>
                                <th>نوع کانفیگ ها</th>
                                <th>Action</th>
                            </tr>
		    			</thead>
		    			<tbody>
                        {% for row in model_obj %}
		    				<tr>
                            <td>{{ row.uid }}</td>
                            {% if row.type_off  %}
                                <th>{{ row.amount }} %</th>
                            {% else %}
                                <th>{{ row.amount }},000 T</th>
                            {% endif %}
                            <td>{% if row.customer_count == 0%}همه{% else %}{{ row.customer_count }}{% endif %}</td>
                            <td dir="rtl">{% if row.use_count == 0%}نامحدود{% else %}{{ row.use_count }} بار {% endif %}</td>
                            <td>{{ row.create_timestamp|timestamp }}</td>
                            <td>{{ row.end_timestamp|timestamp }}</td>
                            <td>{% if row.for_not_infinity %}(حجمی){% endif %}{% if row.for_infinit_usages %}{% endif %} (حجم_نامحدود) {% if row.for_infinit_times %}(زمان_نامحدود){% endif %}</td>

                            <td>
                                <div class="action">
                                    <button class="btn copy delete" onclick="copyToClipboard('#vless_{{ row.id }}')">کپی لینک</button>
                                    <a href="{% url 'bot_finance:delete_off_code' row.uid %}" class="delete">Delete</a>
                                </div>
                                    <p hidden id="vless_{{ row.id }}">tg://resolve?domain={{ bot_username }}&start=off_code_{{ row.uid }}</p>
                            </td>

                            </tr>

                        {% endfor %}
		    			</tbody>
		    		</table>
            </div>


        </div>

<script>
    function copyToClipboard(element) {
          var $temp = $("<textarea>");
          $("body").append($temp);
          var text = $(element).text();
          $temp.val(text).select();
          document.execCommand("copy");
          $temp.remove();
          alert("با موفقیت کپی شد.");
        }
</script>
        <style>
            .copy {
                background-color: #4ac1f7;
            }
            .delete {
                border-radius: 5px;
            }
        </style>
{#		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>#}
{#		<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>#}
		<script src={% static "js/list.js" %}></script>
	</body>
{% include "loading.html" %}

</html>