HiddifyPanel/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.generic.base import RedirectView
from bot_connection.webhook import webhook
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('webhook/', webhook, name='webhook'),
    path("", RedirectView.as_view(url="accounts/home/bot/", permanent=False)),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
    path("bot_finance/", include("bot_finance.urls", namespace="bot_finance")),
    path("bot_customers/", include("bot_customers.urls", namespace="bot_customers")),
    path("servers/", include("servers.urls", namespace="servers")),
    path("bot_config/", include("bot_config.urls", namespace="bot_configs")),
    path("sellers_config/", include("sellers_config.urls", namespace="sellers_configs")),
    path("sellers_finance/", include("sellers_finance.urls"), name="sellers_finance"),
    path("sellers_connection/", include("sellers_connection.urls", namespace="sellers_connection")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path("home/bot/", views.HomeBotView.as_view(), name='home_bot'),
    path("home/sellers/", views.HomeSellersView.as_view(), name='home_sellers'),
    path("settings/", views.SettingsPage.as_view(), name='settings'),
    path("vpn_apps/", views.VpnAppsPage.as_view(), name='vpn_apps'),
    path("delete_app/<int:ind>/", views.DeleteAppPage.as_view(), name='delete_app'),
    path("add_vpn_app/", views.AddAppPage.as_view(), name='add_vpn_app'),
    path("selllers_info/", views.sellers_info.as_view(), name='sellers_info'),
    path("add_seller/", views.AddSellerPage.as_view(), name='add_seller'),
    path("edit_seller/<seller_id>/", views.EditSellerPage.as_view(), name='edit_seller'),
]

bot_config/urls.py
from django.urls import path
from . import views
app_name = 'bot_config'

urlpatterns = [
    path("bot_create_config/<str:form_type>/", views.BotCreateConfigView.as_view(), name="bot_create_config"),
    path("config_page/<uuid:config_uuid>/", views.ConfigPageView.as_view(), name="config_page"),
    path("list_searched_configs/", views.ListConfigsSearched.as_view(), name="list_searched_configs"),
    path("list_configs/", views.ConfigsListView.as_view(), name="list_configs"),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),

]

bot_customers/urls.py
from django.urls import path
from . import views

app_name = "bot_customers"

urlpatterns = [
   path("custumers_list/", views.CustomerList.as_view(), name="custumers_list"),
   path("custumer_detail/<int:customer_id>/", views.CustomerDetail.as_view(), name="custumer_detail"),
   path("send_msg_to_all/", views.SendMsgToAll.as_view(), name="send_msg_to_all"),
   path("send_msg_to_Custumer/<int:userid>/", views.SendMsgToUser.as_view(), name="send_msg_to_user"),
   path("change_wallet/<int:userid>/", views.ChangeWalletAmount.as_view(), name="change_wallet"),
   path("update_customer/<int:userid>/", views.UpdateCustumer.as_view(), name="update_customer"),
   path("register_conf_for_customer/<str:conf_uuid>/", views.RegisterConfigToCustumer.as_view(), name="register_conf_for_customer"),
   path("ban_user/<int:userid>/", views.BanUser.as_view(), name="ban_user"),
]

bot_finance/urls.py
from django.urls import path
from . import views

app_name = "bot_finance"

urlpatterns = [
    path('confirm_payment/<int:show_box>/', views.ConfirmPaymentPage.as_view(), name='confirm_payments'),
    path('first_confirm_payment/<int:obj_id>/', views.FirstConfirmPayment.as_view(), name='first_confirm'),
    path('secoend_confirm_payment/<int:obj_id>/', views.SecondConfirmPayment.as_view(), name='second_confirm'),
    path('first_tamdid_confirm_payment/<int:obj_id>/', views.FirstTamdidConfirmPayment.as_view(), name='first_tamdid_confirm'),
    path('secoend_tamdid_confirm_payment/<int:obj_id>/', views.SecondTamdidConfirmPayment.as_view(), name='second_tamdid_confirm'),

    path('deny_tamdid_payment_after_first_confirm/<int:obj_id>/', views.DenyTamdidPaymentAfterFirsConfirmPage.as_view(),
         name='deny_tamdid_payments_after_first_confirm'),
    path('deny_payment_after_first_confirm/<int:obj_id>/', views.DenyPaymentAfterFirsConfirmPage.as_view(), name='deny_payments_after_first_confirm'),
    path('deny_payment/<int:obj_id>/<str:typ>/', views.DenyPaymentPage.as_view(), name='deny_payments'),
    path('edit_price_payment/<int:obj_id>/<str:typ>/', views.EditPricePayment.as_view(), name='edit_price'),
    path("paid_after_create/<int:obj_id>/", views.PayedAfterCreate.as_view(), name="paid_after_create"),

    path('show_prices/', views.ShowPrices.as_view(), name='show_prices'),
    path('delete_or_edit_price/<int:obj_id>/<str:action>/', views.DeleteOrEditPrice.as_view(), name='delete_or_edit_price'),
    path('add_price/', views.AddPrice.as_view(), name='add_price'),

    path("show_off_codes/", views.ShowOffCodes.as_view(), name='show_off_codes'),
    path("add_off_codes/", views.AddOffCode.as_view(), name='add_off_codes'),
    path("delete_off_code/<str:uuid>/", views.DeleteOffCode.as_view(), name='delete_off_code'),

]

sellers_config/urls.py
from django.urls import path
from . import views
app_name = 'sellers_config'

urlpatterns = [
    path('create_config/<int:seller_id>/', views.CreateConfigView.as_view(), name='create_config'),
    path("list_configs_searched/", views.SearchedConfigsView.as_view(), name='list_configs_searched'),
    path("configs_details/<uuid:uuid>/", views.ConfigDetailView.as_view(), name='config_details'),
    path("list_configs/<int:userid>/", views.ListConfigsView.as_view(), name='list_configs'),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),
]

servers/urls.py
from django.urls import path
from . import views

app_name = 'servers'

urlpatterns = [
    path('show_servers/', views.ShowServers.as_view(), name="show_servers"),
    path("add_server/", views.AddServer.as_view(), name="add_server"),
    path("edit_server/<int:server_id>/", views.EditServer.as_view(), name="edit_server"),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.db import models
from .managers import UserManager
from sellers_connection.models import Bots

class User(AbstractBaseUser):
    username = models.CharField(unique=True, max_length=20)
    is_active = models.BooleanField(default=True)
    level_access = models.PositiveIntegerField(default=0, choices=[(0, 'Seller'), (1, 'SubSeller'), (10, 'Admin')])
    payment_limit = models.PositiveIntegerField(default=0)
    finanace_access = models.BooleanField(default=True)
    create_config_acc = models.BooleanField(default=True)
    list_configs_acc = models.BooleanField(default=True)
    delete_config_acc = models.BooleanField(default=True)
    bot = models.ForeignKey(Bots, on_delete=models.DO_NOTHING,default=1, null=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ["is_active", "level_access"]  # fields that will show in createsuperuser

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        if self.level_access == 10:
            return True
        return False

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
import json
from .models import User
from sellers_connection.models import Bots


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm Password', widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'password', "password2", "level_access"]

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] and cd["password2"] and cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords must match")
        return cd["password2"]

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text="<a href=\"../password/\">change password</a>")
    class Meta:
        model = User
        fields = ['username', "password", "level_access"]


class LoginForm(forms.Form):
    username = forms.CharField(label="یوزرنیم:")
    password = forms.CharField(widget=forms.PasswordInput(), label="رمز عبور:")

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is None:
            raise ValidationError("یوزرنیم یا پسوورد اشتباه است.")



class AddUserForm(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField()
    password2 = forms.CharField()

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if " " in username or " " in password:
            raise ValidationError("username or password can not contain space.")

        if not username and not password and not password2:
            raise ValidationError("enter username and password")

        if password != password2:
            raise ValidationError("Passwords must match")

        if User.objects.filter(username=username).exists():
            raise ValidationError("Username already exists")



class ChangeSettingForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        with open("settings.json", "r", encoding="utf-8") as f:
            j = json.load(f)
        self.fields["card_number"].initial = j["pay_card_number"]
        self.fields["card_name"].initial = j["pay_card_name"]
        self.fields["prices_msg_id"].initial = j["prices_msg_id"]
        self.fields["U1_1M"].initial = j["unlimit_limit"]["1u"]["1m"]
        self.fields["U1_2M"].initial = j["unlimit_limit"]["1u"]["2m"]
        self.fields["U1_3M"].initial = j["unlimit_limit"]["1u"]["3m"]
        self.fields["U2_1M"].initial = j["unlimit_limit"]["2u"]["1m"]
        self.fields["U2_2M"].initial = j["unlimit_limit"]["2u"]["2m"]
        self.fields["U2_3M"].initial = j["unlimit_limit"]["2u"]["3m"]
        self.fields["config_name_counter"].initial = j["config_name_counter"]


    card_number = forms.IntegerField()
    card_name = forms.CharField(max_length=25)
    prices_msg_id = forms.IntegerField()
    U1_1M = forms.IntegerField()
    U1_2M = forms.IntegerField()
    U1_3M = forms.IntegerField()
    U2_1M = forms.IntegerField()
    U2_2M = forms.IntegerField()
    U2_3M = forms.IntegerField()
    config_name_counter = forms.IntegerField()


    def clean_card_number(self):
        card_number = self.cleaned_data["card_number"]
        if len(str(card_number)) != 16:
            raise ValidationError("شماره کارت باید 16 رقمی باشد.")
        return card_number

    def clean_config_name_counter(self):
        config_name_counter = self.cleaned_data["config_name_counter"]
        with open("settings.json", "r", encoding="utf-8") as f:
            last = json.load(f)["config_name_counter"]
            if config_name_counter > last:
                return config_name_counter
            else:
                return last + 1


class VpnAppsForm(forms.Form):
    app_name = forms.CharField(max_length=25,required=False)
    download_url = forms.URLField(required=False)
    guid = forms.IntegerField(required=False)


class SellersAccessesForm(forms.Form):
    username = forms.CharField(max_length=20, required=False)
    password = forms.CharField(required=False)
    level_access = forms.ChoiceField(choices=[("0", "فروشنده معمولی"), ("1", "فروشنده عمده(دارای زیرمجموعه)")], required=False)
    payment_limit = forms.IntegerField(min_value=0, max_value=99000)
    finanace_access = forms.BooleanField(initial=True, required=False)
    create_config_acc = forms.BooleanField(initial=True, required=False)
    list_configs_acc = forms.BooleanField(initial=True, required=False)
    delete_config_acc = forms.BooleanField(initial=True, required=False)
    bot = forms.ChoiceField(choices=[(str(i.bot_uuid), i.name) for i in Bots.objects.all()])

    def clean_level_access(self):
        level = self.cleaned_data["level_access"]
        return int(level)

    def clean_username(self):
        username = self.cleaned_data["username"]
        if " " in username:
            raise ValidationError("username cant containe space.")
        if User.objects.filter(username=username).exists():
            raise ValidationError("username already exists")
        return username

accounts/templates/add_seller.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'create_form.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bot_config/create_config.css' %}">
</head>
<body>
{% include "navbar_sellers.html" %}
{% include 'messages.html' %}
<div id="main">
    <div id="zx">
    </div>
        <form novalidate action="" method="post" dir="rtl">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
        {% if edit %}
            <h3 id="title">ویرایش / {{ usernamr }}</h3>
        {% else %}
            <h3 id="title">فروشنده جدید</h3>
        {% endif %}

            {% csrf_token %}

            <div class="textinput item"><h3 class="item_text">یوزرنیم:</h3>{{ form.username }}</div>
            <div class="textinput item"><h3 class="item_text">پسوورد:</h3>{{ form.password }}</div>
            {% if edit %}
            <script>
                $(document).ready(function() {
                    $("#id_username").prop("disabled", true);
                    $("#id_password").prop("disabled", true);
                });
            </script>
            {% endif %}
            <div id="time_limit" class="textinput item"><h3 class="item_text">نقش : </h3>{{ form.level_access }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">محدودیت خرید : </h3>{{ form.payment_limit }} هزار تومان / 0 = بدون محدودیت</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">بات تلگرام : </h3>{{ form.bot }}</div>
            <hr style="color: #000d3f;background-color: #000d3f">
            <h3 id="title" style="font-size: large">دسترسی ها</h3>
            <div id="time_limit" class="textinput item"><h3 class="item_text">قیمت و صورتحساب : </h3>{{ form.finanace_access }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">ساخت کانفیگ : </h3>{{ form.create_config_acc }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">لیست کانفیگ : </h3>{{ form.list_configs_acc }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">حذف کانفیگ : </h3>{{ form.delete_config_acc }}</div>
            <input id="create" class="submit_btn" type="submit" value="Create">
        </form>
    </div>
<style>
    #id_finanace_access,
    #id_create_config_acc,
    #id_list_configs_acc,
    #id_delete_config_acc{
        width: 1.2rem ;
        height: 1.2rem;
    }
</style>
{% include "loading.html" %}

</body>
</html>

accounts/templates/home_bot.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home_page.css' %}">
    <script>
        $(document).ready(function() {
            $('#create_config_box').hide()
            $('#list_config_box').hide()
            $('#create_config').click(function () {
                $('#main').hide()
                $('#create_config_box').show()
                }
            )
            $('#list_config').click(function () {
                $('#main').hide()
                $('#list_config_box').show()
                }
            )
            $('.close_btn').click(function () {
                $('#create_config_box').hide()
                $('#list_config_box').hide()
                $('#main').show()
            })
        });
    </script>

</head>

<body dir="rtl">

    <header dir="ltr" class="header">
    <h1 class="logo"><a id="logo" href="{% url 'accounts:home_bot' %}">NapsV Telegram BOT</a></h1>
    <ul class="main-nav">
        <div class="dropdown www">
            <h3 dir="rtl" class="dropbtn" id="user boxx" >
                <div class="boz">
                    <span id="username">{{ user.username }}</span>
                    <img id="usericon" src="{% static "img/user.png" %}" alt="user">
                </div>
            </h3>
            <div class="dropdown-content">
                <a href="{% url 'accounts:logout' %}">خروج از حساب</a>
            </div>
        </div>
        <li id="cahnge_li" ><a  class="www" id="home change_a" href='{% url 'accounts:home_sellers' %}'><img
                src="{% static "img/change.png" %}" id="usericon" alt=""> Panel</a></li>

        <style>
            #cahnge_li {
                display: flex;
                flex-direction: row;
                width:35vw;
                justify-content:space-around;
                align-content: center;
                align-items: center;
                justify-items: center;
                padding: 0;
            }
            #change_a {
                width: max-content;
                padding: 0.6rem 0;
                margin: 0;
                align-content: center;
                display:flex;
                flex-direction: row;
                flex-wrap: nowrap;
                text-align: center
            }
        </style>
        <li class="hidephone"><a class="www" href="{% url "bot_config:bot_create_config" "auto" %}" id="action_create_config">ساخت کانفیگ</a></li>
        <li class="hidephone"><a class="www" href="{% url "bot_configs:list_configs" %}" id="action_list_config">لیست کانفیگ ها</a></li>
    </ul>
</header>
    {% include 'messages.html' %}
    <div id="main">
        <div id="box1">
            <div id="searchbox">
                <form novalidate action="{% url 'bot_config:list_searched_configs' %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-config.png' %}" alt="search">
                    {{ search_config.search_config }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
                <form novalidate action="{% url 'bot_customers:custumers_list' %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-user.png' %}" alt="search">
                    {{ search_user.search_user }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
            </div>
            <a href="{% url 'bot_finance:confirm_payments' 1 %}" class="links link2" id="pay_confirm">✅ تایید پرداخت 💳</a>
            <a href="{% url "bot_config:bot_create_config" "auto" %}" class="links link2">➕ ساخت کانفیگ 🔗</a>
            <a href="{% url "bot_configs:list_configs" %}" class="links link2">📋 لیست کانفیگ ها 🔗</a>
            <a href="{% url 'servers:show_servers' %}" class="links" id="servers">🌐 سرور ها 📶</a>
            <a href="{% url 'bot_customers:custumers_list' %}" class="links" id="customers">👥 مشتری ها 🤖</a>
{#            <a href="{% url "reports:admin_logs" %}" class="links" id="setting">🗃️ Admin Log 👨🏻‍🔧</a>#}
{#            <a href="{% url "reports:pay_logs" %}" class="links" id="setting">🗃️ Pays Log 💰</a>#}
{#            <a href="{% url "reports:celery_delete_conf_logs" %}" class="links" id="setting">🗃️ Celery Log 🗑</a>#}
{#            <a href="{% url "reports:send_msgs_log" %}" class="links" id="setting">🗃️ MSG Log 📨</a>#}
            <a href="{% url 'bot_customers:send_msg_to_all' %}" class="links" id="message">️📝 پیام همگانی 📨</a>
            <a href="{% url 'bot_finance:show_prices' %}" class="links" id="tarefeh">💰 تعرفه ها 🛒</a>
{#            <a href="{% url "reports:reports" %}" class="links" id="report">📊 گزارشات 📈</a>#}
            <a href="{% url 'bot_finance:show_off_codes' %}" class="links" id="tarefeh">💲 کد تخفیف 🆓</a>
            <a href="{% url "accounts:settings" %}" class="links" id="setting">⚙️ تنظیمات 🛠️</a>
            <a href="{% url "accounts:vpn_apps" %}" class="links" id="setting">💻 Apps 📱️</a>
{#            <a href="" class="links" id="setting">❗️ Errors ❗️</a>#}
        </div>
    </div>


{% include "loading.html" %}
</body>
</html>

accounts/templates/home_sellers.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home_page.css' %}">
    <script>
        $(document).ready(function() {
            $('#create_config_box').hide()
            $('#list_config_box').hide()
            $('#prices_box').hide()
            $('#create_config').click(function () {
                $('#main').hide()
                $('#create_config_box').show()
                }
            )
            $('#list_config').click(function () {
                $('#main').hide()
                $('#list_config_box').show()
                }
            )
            $('#select_prices').click(function () {
                $('#main').hide()
                $('#prices_box').show()
                }
            )
            $('.close_btn').click(function () {
                $('#create_config_box').hide()
                $('#prices_box').hide()
                $('#list_config_box').hide()
                $('#main').show()
            })

        });
    </script>

</head>

<body dir="rtl">

    <header dir="ltr" class="header">
    <h1 class="logo"><a id="logo" href="{% url 'accounts:home_bot' %}">NapsV Panel</a></h1>
    <ul class="main-nav">
        <div class="dropdown www">
            <h3 dir="rtl" class="dropbtn" id="user boxx" >
                <div class="boz">
                    <span id="username">{{ user.username }}</span>
                    <img id="usericon" src="{% static "img/user.png" %}" alt="user">
                </div>
            </h3>
            <div class="dropdown-content">
                <a href="{% url 'accounts:logout' %}">خروج از حساب</a>
            </div>
        </div>
        {% if user.level_access == 10 %}
        <li id="cahnge_li" ><a  class="www" id="home change_a" href='{% url 'accounts:home_bot' %}'><img
                src="{% static "img/change.png" %}" id="usericon" alt=""> Panel</a></li>
        {% endif %}
        <style>
            #cahnge_li {
                display: flex;
                flex-direction: row;
                width:35vw;
                justify-content:space-around;
                align-content: center;
                align-items: center;
                justify-items: center;
                padding: 0;
            }
            #change_a {
                width: max-content;
                padding: 0.6rem 0;
                margin: 0;
                align-content: center;
                display:flex;
                flex-direction: row;
                flex-wrap: nowrap;
                text-align: center
            }
        </style>
    </ul>
</header>
    {% include 'messages.html' %}
    <div id="main">
        <div id="box1">
            <div id="searchbox">
                <form novalidate action="{% url 'sellers_config:list_configs_searched' %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-config.png' %}" alt="search">
                    {{ search_config.search_config }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
            </div>
        {% if user.level_access == 0 %}
            <a href="{% url "sellers_config:create_config" user.id %}" class="links link2">➕ ساخت کانفیگ 🔗</a>
            <a href="{% url "sellers_config:list_configs" user.id %}" class="links link2">📋 لیست کانفیگ ها 🔗</a>
        {% else %}
            <button class="links link2" id="create_config">➕ ساخت کانفیگ 🔗</button>
            <button class="links link2" id="list_config">📋 لیست کانفیگ ها 🔗</button>
        {% endif %}
        {% if not user.level_access == 10 %} {# and finance accsess #}
            <a href="{% url "sellers_finance:seller_payment_page" user.id %}" class="links link2" id="customers">💵 صورت حساب 💳</a>
        {% else %}
            <a href="{% url "sellers_finance:payments_page" %}" class="links link2" id="customers">💵 صورت حساب 💳</a>
        {% endif %}

        {% if user.level_access == 0 %}
            <a href="{% url "sellers_finance:sellers_show_prices" user.id %}" class="links">💰 تعرفه ها 🛒</a>
        {% else %}
            <button id="select_prices" class="links">💰 تعرفه ها 🛒</button>
        {% endif %}
            <a href="" class="links" id="setting">🗃️  Logs 👨🏻‍🔧</a>
            <a href="{% url 'accounts:sellers_info' %}" class="links" id="setting">👤 فروشنده ها 🛠️</a>
            <a href="" class="links" id="setting">📶 Status 📑</a>
            {% if not user.level_access == 0 %}
                <a href="" class="links" id="message">️📝 پیام همگانی 📨</a>
                <a href="" class="links" id="report">📊 گزارشات 📈</a>
            {% endif %}

        {% if user.level_access == 10 %}
            <a href="{% url "sellers_connection:list_bots" %}" class="links" id="setting">⚙️ بات های تلگرام 🤖️</a>
            <a href="" class="links" id="setting">⚙️ تنظیمات 🛠️</a>
        {% endif %}

        </div>
    </div>
        <div class="servers" id="prices_box">
        <div class="closebox"><button class="close_btn">✖️</button></div>
        <h3>تعرفه ها</h3>
            <div class="server_lists" >
                {% if not user.level_access == 10 %}
                <a class="server_name" href="{% url "sellers_finance:sellers_show_prices" user.id %}">{{ user.username }} 👤</a>
                {% endif %}
                {% for s in sellers_list %}
                    <a class="server_name" href="{% url "sellers_finance:sellers_show_prices" s.id %}">{{ s.username }} 👤</a>
                {% endfor %}
        </div>

    </div>
    <style>

    </style>

{% include "subsellers_list.html" %}
{% include "loading.html" %}
</body>
</html>