HiddifyPanel/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.generic.base import RedirectView
from bot_connection.webhook import webhook
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('webhook/', webhook, name='webhook'),
    path("", RedirectView.as_view(url="accounts/home/bot/", permanent=False)),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('admin/', admin.site.urls),
    path("bot_finance/", include("bot_finance.urls", namespace="bot_finance")),
    path("bot_customers/", include("bot_customers.urls", namespace="bot_customers")),
    path("servers/", include("servers.urls", namespace="servers")),
    path("bot_config/", include("bot_config.urls", namespace="bot_configs")),
    path("sellers_config/", include("sellers_config.urls", namespace="sellers_configs")),
    path("sellers_finance/", include("sellers_finance.urls"), name="sellers_finance"),
    path("sellers_connection/", include("sellers_connection.urls", namespace="sellers_connection")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot_config/urls.py
from django.urls import path
from . import views
app_name = 'bot_config'

urlpatterns = [
    path("bot_create_config/<str:form_type>/", views.BotCreateConfigView.as_view(), name="bot_create_config"),
    path("config_page/<uuid:config_uuid>/", views.ConfigPageView.as_view(), name="config_page"),
    path("list_searched_configs/", views.ListConfigsSearched.as_view(), name="list_searched_configs"),
    path("list_configs/", views.ConfigsListView.as_view(), name="list_configs"),


    path("api_get_config_time_chices/", views.ApiGetConfigTimeChoices.as_view(), name="api_get_time_choices"),
    path("api_get_config_usage_chices/", views.ApiGetConfigUsageChoices.as_view(), name="api_get_usage_choices"),
    path("api_get_config_ip_limit_chices/", views.ApiGetConfigIPLimitChoices.as_view(), name="api_get_iplimit_choices"),
    path("api_get_axact_price/", views.ApiGetConfigPriceChoices.as_view(), name="api_get_axact_price"),

]

bot_customers/urls.py
from django.urls import path
from . import views

app_name = "bot_customers"

urlpatterns = [
   path("custumers_list/", views.CustomerList.as_view(), name="custumers_list"),
   path("custumer_detail/<int:customer_id>/", views.CustomerDetail.as_view(), name="custumer_detail"),
   path("send_msg_to_all/", views.SendMsgToAll.as_view(), name="send_msg_to_all"),
   path("send_msg_to_Custumer/<int:userid>/", views.SendMsgToUser.as_view(), name="send_msg_to_user"),
   path("change_wallet/<int:userid>/", views.ChangeWalletAmount.as_view(), name="change_wallet"),
   path("update_customer/<int:userid>/", views.UpdateCustumer.as_view(), name="update_customer"),
   path("register_conf_for_customer/<str:conf_uuid>/", views.RegisterConfigToCustumer.as_view(), name="register_conf_for_customer"),
   path("ban_user/<int:userid>/", views.BanUser.as_view(), name="ban_user"),
]

servers/urls.py
from django.urls import path
from . import views

app_name = 'servers'

urlpatterns = [
    path('show_servers/', views.ShowServers.as_view(), name="show_servers"),
    path("add_server/", views.AddServer.as_view(), name="add_server"),
    path("edit_server/<int:server_id>/", views.EditServer.as_view(), name="edit_server"),
]

bot_config/models.py
from django.db import models
from bot_customers.models import Customer
from servers.models import Server


class BotConfigInfo(models.Model):
    name = models.CharField(max_length=40, null=False)
    uuid = models.UUIDField(null=False, unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    price = models.PositiveIntegerField(default=0)
    paid = models.BooleanField(default=True)
    created_by = models.CharField(max_length=20, default="BOT")
    renew_count = models.IntegerField(default=0)
    usage_limit = models.IntegerField(default=0)
    days_limit = models.IntegerField(default=0)
    start_timestamp = models.PositiveIntegerField(null=True)
    user_limit = models.PositiveIntegerField(default=0)
    enable = models.BooleanField(default=True)
    update = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class BotInfinitCongisLimit(models.Model):
    config = models.OneToOneField(BotConfigInfo, on_delete=models.CASCADE)
    limit = models.IntegerField()


class BotConfigsEveryServerUsage(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    config = models.ForeignKey(BotConfigInfo, on_delete=models.CASCADE)
    usage_now = models.FloatField(default=0)
    update_timestamp = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.server.name + self.config.name

bot_config/forms.py
from django import forms
from bot_finance.models import Prices
from django.core.exceptions import ValidationError

class CreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = [('limited','حجمی')]
        if Prices.objects.filter(usage_limit=0).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if Prices.objects.filter(expire_limit=0).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types

    type = forms.ChoiceField(required=False,)
    usage_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    days_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    ip_limit = forms.CharField(required=False, widget=forms.Select(choices=[]))
    paid = forms.BooleanField(required=False, initial=True)
    def clean_usage_limit(self):
        return self.cleaned_data.get('usage_limit')
    def clean_days_limit(self):
        return self.cleaned_data.get('days_limit')
    def clean_ip_limit(self):
        return self.cleaned_data.get('ip_limit')



class ManualCreateConfigForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = self.type_limit()
    def type_limit(self):
        types = [('limited','حجمی')]
        if Prices.objects.filter(usage_limit=0).exists():
            types.append(('usage_unlimit', "حجم نامحدود"))
        if Prices.objects.filter(expire_limit=0).exists():
            types.append(('time_unlimit', "زمان نامحدود"))
        return types



    type = forms.ChoiceField(required=False)
    usage_limit = forms.IntegerField(required=False)
    days_limit = forms.IntegerField(required=False)
    ip_limit = forms.ChoiceField(required=False, choices=[(1, '1 کاربره'), (2, '2 کاربره')])
    price = forms.IntegerField(required=False)
    paid = forms.BooleanField(required=False, initial=True)

    def clean_price(self):
        price = self.cleaned_data['price']
        if price is None:
            raise ValidationError('قیمت را وارد کنید.')
        elif not 0 <= price < 1500:
            raise ValidationError('قیمت باید بین 0 تا 1500 هزار تومان باشد.')
        return price

    def clean(self):
        type = self.cleaned_data.get('type')
        usage_limit = self.cleaned_data.get('usage_limit')
        days_limit = self.cleaned_data.get('days_limit')
        if type == "limited":
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'usage_unlimit':
            if days_limit is None:
                raise ValidationError('مدت زمان کانفیگ را وارد کنید.')
            elif not 0 < days_limit < 365:
                raise ValidationError('مدت زمان کانفیگ باید بین 1 روز تا 365 روز باشد.')
        elif type == 'time_unlimit':
            if usage_limit is None:
                raise ValidationError('حجم کانفیگ را وارد کنید.')
            elif not 1 < usage_limit < 1000:
                raise ValidationError('حجم کانفیگ باید بین 1 تا 1000 گیگ باشد.')

class SearchConfigForm(forms.Form):
    search_config = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Search Config Name or UUID'}))

bot_config/views.py
from django.shortcuts import render,redirect
from bot_finance.models import Prices
from bot_config.actions import BotAction
from servers.models import Server
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from rest_framework.views import APIView
from rest_framework.response import Response
from time import sleep
from django.db.models import Q
from .forms import CreateConfigForm, ManualCreateConfigForm
from .models import BotConfigInfo, BotConfigsEveryServerUsage
from utils import now_timestamp
from django.contrib import messages
from .forms import SearchConfigForm


class BotCreateConfigView(LoginRequiredMixin, View):
    def get(self, request, form_type):
        forms = {'auto': CreateConfigForm, 'manual': ManualCreateConfigForm}
        return render(request, 'create_config.html',
                      {'form': forms[form_type],
                       'form_type': form_type})

    def post(self, request, form_type):
        forms = {'auto': CreateConfigForm, 'manual': ManualCreateConfigForm}
        form = forms[form_type](request.POST)
        if form.is_valid():
            ip_limit = 0
            days_limit = 0
            usage_limit = 0
            cd = form.cleaned_data

            if cd['type'] == "limited":
                usage_limit = int(cd["usage_limit"])
                days_limit = int(cd['days_limit'])
            elif cd['type'] == 'usage_unlimit':
                days_limit = int(cd['days_limit'])
                ip_limit = int(cd['ip_limit'])
            elif cd['type'] == 'time_unlimit':
                usage_limit = int(cd["usage_limit"])

            if form_type == 'auto':
                price = Prices.objects.get(usage_limit=usage_limit, expire_limit=days_limit, user_limit=ip_limit).price
            else:
                price = cd['price']
            paid = cd["paid"]
            if form_type == 'auto':
                days_limit = days_limit * 30
            create_config = BotAction.create_config_by_admins(days_limit, usage_limit, ip_limit, price, paid, request.user.username)
            print(create_config)
            return redirect('bot_config:config_page',create_config)


        return render(request, 'create_config.html',
                      {'form': form, 'form_type': form_type})


class ConfigPageView(LoginRequiredMixin, View):
    def get(self, request, config_uuid):
        config_infos = BotConfigInfo.objects.get(uuid=config_uuid)
        usage = 0
        for us in BotConfigsEveryServerUsage.objects.filter(config__uuid=config_uuid):
            usage += us.usage_now
        if not config_infos.start_timestamp:
            started = False
            days_remain = config_infos.days_limit
        else:
            started = True
            days_remain = ((config_infos.start_timestamp + (config_infos.days_limit * 86400)) - now_timestamp()) / 86400

        return render(request, "config_page.html", {"config_info": config_infos, "usage": usage,
                        "days_remain": days_remain, "started":started})


class ListConfigsSearched(LoginRequiredMixin, View):
    def post(self, request):
        form = SearchConfigForm(request.POST)
        if form.is_valid():
            word = form.cleaned_data["search_config"]
            model_obj = BotConfigInfo.objects.filter(Q(name__icontains=word) | Q(uuid__icontains=word))
            if not model_obj.exists():
                messages.error(request, 'کانفیگی با این مشخصات یافت نشد.')
            return render(request, "list_configs_searched.html",
                          {"configs_model": reversed(model_obj), "search_config": form})
        return redirect('accounts:home_bot')


class ConfigsListView(ListConfigsSearched, View):

    def get(self, request, *args, **kwargs):
        query_string = request.META['QUERY_STRING']
        if query_string.startswith("search="):
            searched = query_string.split("search=")[1]
        else:
            searched = False
        print(searched)
        list_configs = []
        configs = BotConfigInfo.objects.all().order_by("-update", "-name")
        now_time = now_timestamp()
        for config in configs:
            if searched:
                if not searched.lower() in config.name.lower() and not searched.lower() in str(config.uuid):
                    continue
            sum_usage = 0
            for usages in config.botconfigseveryserverusage_set.all():
                sum_usage += usages.usage_now
            end_usage = False if config.usage_limit == 0 or sum_usage < config.usage_limit else True
            if config.start_timestamp:
                remain = ((config.start_timestamp + (config.days_limit * 86400)) - now_time) / 86400
                expired = True if remain < 0 else False
            else:
                expired = False
                remain = config.days_limit
            list_configs.append({"config":config, "sum_usage": sum_usage, "remain": remain, "expired": expired, "end_usage":end_usage})
        return render(request, "list_configs.html", {"list_configs": list_configs, "searched":searched})






# create config by admin api
class ApiGetConfigTimeChoices(APIView):
    def get(self, request):
        sleep(0.25)
        type = request.GET.get('type')
        choices = []
        if type == 'limited':
            obj = Prices.objects.filter(~Q(usage_limit=0) & ~Q(expire_limit=0))
            for i in obj:
                if not (i.expire_limit, f"{i.expire_limit} ماه") in choices:
                    choices.append((i.expire_limit, f"{i.expire_limit} ماه"))
        elif type == 'usage_unlimit':
            obj = Prices.objects.filter(Q(usage_limit=0) & ~Q(expire_limit=0))
            for i in obj:
                if not (i.expire_limit, f"{i.expire_limit} ماه") in choices:
                    choices.append((i.expire_limit, f"{i.expire_limit} ماه"))
        elif type == 'time_unlimit':
            choices.append((0, '∞'))

        choices = sorted(choices, key=lambda x: x[0])
        return Response({'choices': choices})


class ApiGetConfigUsageChoices(APIView):
    def get(self, request):
        type = request.GET.get('type')
        time = int(request.GET.get('time'))
        choices = []
        if type == 'limited':
            time = time
            obj = Prices.objects.filter(~Q(usage_limit=0) & Q(expire_limit=time))
            for i in obj:
                if not (i.usage_limit, f"{i.usage_limit} GB") in choices:
                    choices.append((i.usage_limit, f"{i.usage_limit} GB"))

        elif type == 'usage_unlimit':
            choices.append((0, '∞'))

        elif type == 'time_unlimit':
            obj = Prices.objects.filter(~Q(usage_limit=0) & Q(expire_limit=0))
            for i in obj:
                if not (i.usage_limit, f"{i.usage_limit} GB") in choices:
                    choices.append((i.usage_limit, f"{i.usage_limit} GB"))

        choices = sorted(choices, key=lambda x: x[0])
        return Response({'choices': choices})


class ApiGetConfigIPLimitChoices(APIView):
    def get(self, request):
        type = request.GET.get('type')
        time = int(request.GET.get('time'))

        choices = []
        if type == 'limited' or type == 'time_unlimit':
            choices.append((0, '∞'))

        elif type == 'usage_unlimit':
            time = time
            obj = Prices.objects.filter(Q(usage_limit=0) & Q(expire_limit=time))
            for i in obj:
                if not (i.user_limit, f"{i.user_limit} کاربره") in choices:
                    choices.append((i.user_limit, f"{i.user_limit} کاربره"))

        choices = sorted(choices, key=lambda x: x[0])
        return Response({'choices': choices})


class ApiGetConfigPriceChoices(APIView):
    def get(self, request):
        time = int(request.GET.get('time'))
        iplimit = int(request.GET.get('iplimit'))
        usage = int(request.GET.get('usage'))
        obj = Prices.objects.get(usage_limit=usage, expire_limit=time, user_limit=iplimit).price
        return Response({'price': f'{obj:,}'})

bot_config/templates/create_config.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "base_head.html" %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'create_form.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bot_config/create_config.css' %}">
</head>
<body>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let type = document.querySelector('#id_type');
        let usage = document.querySelector('#usage');
        let time_limit = document.querySelector("#time_limit")
        let ip_limit = document.querySelector('#ip_limit')
        function toggleexpireField() {
            if (type.value === "limited") {
                time_limit.style.display = "block"
                usage.style.display = "block"
                ip_limit.style.display = "none"
            }
            else if (type.value === 'time_unlimit') {
                time_limit.style.display = "none"
                usage.style.display = "block"
                ip_limit.style.display = "none"
            }
            else if (type.value === 'usage_unlimit'){
                time_limit.style.display = "block"
                usage.style.display = "none"
                ip_limit.style.display = "block"
            }
        }

        type.addEventListener('change', toggleexpireField);
        toggleexpireField();
    });
</script>
{% include "navbar_bot.html" %}
{% include 'messages.html' %}
<div id="main">
    <div id="zx">
    {% if form_type == 'auto' %}
        <a href="{% url 'bot_config:bot_create_config' 'manual' %}" class="change_form">کانفیگ دستی</a>
    {% else %}
        <a href="{% url 'bot_config:bot_create_config' 'auto' %}" class="change_form">کانفیگ خودکار</a>
    {% endif %}
    </div>
        <form novalidate action="" method="post" dir="rtl">
            {% for field_errors in form.errors.values %}
              {% for error in field_errors %}
                  <p dir="rtl" class="errors">{{ error }}</p>
              {% endfor %}
            {% endfor %}
            <h3 id="title">ساخت کانفیگ جدید</h3>
            {% csrf_token %}
            <h3 id="title">{{ server.server_name }}</h3>
            <div class="textinput item"><h3 class="item_text">نوع کانفیگ : </h3>{{ form.type }}</div>
            <div id="time_limit" class="textinput item"><h3 class="item_text">مدت زمان کانفیگ : </h3>{{ form.days_limit }}{% if form_type == 'manual' %}🔺 روز{% endif %}</div>
            <div id="usage" class="textinput item"><h3 class="item_text">حجم کانفیگ : </h3>{{ form.usage_limit }}{% if form_type == 'manual' %}GB{% endif %}</div>
            <div id="ip_limit" class="textinput item"><h3 class="item_text">تعداد کاربر : </h3>{{ form.ip_limit }}</div>
            {% if form_type == 'auto' %}
            <h3 class="item_text" dir="ltr" style="display:inline-block; ">: قیمت<div class="loader2" dir="ltr" id="price_loading"></div><h4 id="pricespan"> </h4></h3>
            <div id="divloader" style="display: flex; align-items: center"><div class="loader" id="subloader"></div></div>
            {% else %}
            <div id="price" class="textinput item"><h3 class="item_text"> قیمت : </h3>{{ form.price }} هزار تومان</div>
            {% endif %}
            <div id="paid" class="textinput item paid_text">پرداخت شده : {{ form.paid }}</div>
            <input id="create" class="submit_btn" type="submit" value="Create">
        {% if form_type == "auto" %}
            <script>
    const days_limit = document.getElementById('id_days_limit');
    const usage_limit = document.getElementById('id_usage_limit');
    const type = document.getElementById('id_type');
    const ip_limit = document.getElementById('id_ip_limit');
    const h3Element = document.getElementById('pricespan');
    const submitButton = document.getElementById('create');
    const subloader = document.getElementById('subloader');
    const priceloading = document.getElementById('price_loading');
    function fetchTimeChoices() {
        days_limit.disabled = true;
        usage_limit.disabled = true;
        ip_limit.disabled = true;
        submitButton.style.display = 'none';
        subloader.style.display = 'block';
        priceloading.style.display = 'block';
        const otherField2Value = type.value;
        const url = `{% url "bot_config:api_get_time_choices" %}?type=${otherField2Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                {#h3Element.textContent = data;#}
                days_limit.innerHTML = '';
                data.choices.forEach(choice => {
                    const option = document.createElement('option');
                    option.value = choice[0];
                    option.text = choice[1];
                    days_limit.add(option);

                });
                submitButton.style.display = 'block';
                subloader.style.display = 'none';
                days_limit.disabled = false;
                fetchUsageChoices()
            });

    }
    function fetchUsageChoices() {
        usage_limit.disabled = true;
        ip_limit.disabled = true;
        submitButton.style.display = 'none';
        subloader.style.display = 'block';
        priceloading.style.display = 'block';
        const otherField2Value = type.value;
        const otherField1Value = days_limit.value;
        const url = `{% url "bot_config:api_get_usage_choices" %}?type=${otherField2Value}&time=${otherField1Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                {#h3Element.textContent = data;#}
                usage_limit.innerHTML = '';
                data.choices.forEach(choice => {
                    const option = document.createElement('option');
                    option.value = choice[0];
                    option.text = choice[1];
                    usage_limit.add(option);

                });
                submitButton.style.display = 'block';
                subloader.style.display = 'none';
                usage_limit.disabled = false;
                fetchIPLimitChoices()
            });

    }
    function fetchIPLimitChoices() {
        submitButton.style.display = 'none';
        ip_limit.disabled = true;
        subloader.style.display = 'block';
        priceloading.style.display = 'block';
        const otherField2Value = type.value;
        const otherField1Value = days_limit.value;
        const url = `{% url "bot_config:api_get_iplimit_choices" %}?type=${otherField2Value}&time=${otherField1Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                {#h3Element.textContent = data;#}
                ip_limit.innerHTML = '';
                data.choices.forEach(choice => {
                    const option = document.createElement('option');
                    option.value = choice[0];
                    option.text = choice[1];
                    ip_limit.add(option);
                    ip_limit.disabled = false;
                });
                submitButton.style.display = 'block';
                subloader.style.display = 'none';

                price();
            });

    }
    function price() {
        days_limit.disabled = false;

        priceloading.style.display = 'block';
        const otherField1Value = usage_limit.value;
        const otherField2Value = type.value;
        const otherField3Value = days_limit.value;
        const otherField4Value = ip_limit.value;
        const url = `{% url "bot_config:api_get_axact_price" %}?usage=${otherField1Value}&type=${otherField2Value}&time=${otherField3Value}&iplimit=${otherField4Value}`;
        h3Element.textContent = ``;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                    h3Element.textContent = `T ${data.price}`;
                    priceloading.style.display = 'none';
                    submitButton.style.display = 'block';
            });

    }
    fetchTimeChoices();
    type.addEventListener('change', fetchTimeChoices);
    days_limit.addEventListener('change', fetchUsageChoices)
    usage_limit.addEventListener('change', fetchIPLimitChoices);
    ip_limit.addEventListener('change', price);
</script>
        {% endif %}
        </form>
    </div>
{% include "loading.html" %}

</body>
</html>

bot_config/templates/list_configs_searched.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="fa" class="no-js">
	<head>
		<title>List Configs</title>
        {% include "base_head.html" %}
        <link rel="stylesheet" type="text/css" href="{% static 'component.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'bot_customers/list_custumers.css' %}" />
    </head>
	<body dir="ltr">
        {% include "navbar_bot.html" %}
        {% include 'messages.html' %}
            <div id="main">

            <h3 id="title">جستجو در کانفیگ های ثبت شده</h3>
            <form novalidate action="{% url 'bot_config:list_searched_configs' %}" class="serch_box_inside" method="post">
                    {% csrf_token %}
                    <img class="search_img" src="{% static 'img/search-config.png' %}" alt="search">
                    {{ search_config.search_config }}
                    <input class="input_btn submit_btn" type="submit" value="🔍">
                </form>
		    <div class="xcontainer">
		    		<table class="overflow-y">
		    			<thead>
		    				<tr>
                                <th>Config Name</th>
                                <th>For User</th>
                                <th>UUID</th>
		    				</tr>
		    			</thead>
		    			<tbody>
                        {% for conf in configs_model %}
                            <tr>
                                <td><a href="{% url 'bot_config:config_page' conf.uuid %}">{{ conf.name }}</a></td>
                                {% if conf.chat_id.userid == none %}
                                <td>ثبت نشده</td>
                            {% else %}
                                <td><a href="{% url 'customers:custumer_detail' conf.customer.chat_id %}">{{ conf.customer.chat_id }}</a></td>
                            {% endif %}
                                <td>{{ conf.uuid }}</td>
                            </tr>


                        {% endfor %}
		    			</tbody>
		    		</table>
            </div>
        </div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-throttle-debounce/1.1/jquery.ba-throttle-debounce.min.js"></script>
		<script src={% static "js/list.js" %}></script>
	</body>

{% include "loading.html" %}

</html>